#!/usr/bin/env python3
"""Toplu v4 çıkarımı: projeleri indir, cikar_bin.py ile derle/çıkar, tekilleştir, ayır.

  python3 olcekle.py indir    --liste projeler.json .notlar/aday-projeler.json [--ad x y] [--pilot 20]
  python3 olcekle.py cikar    --liste ... [--pilot 20] [-j 3]
  python3 olcekle.py birlestir [--pilot]

Çıktılar git dışında: veri/bin/olcek/ham/<rol>/<ad>.jsonl (proje başına), veri/bin/olcek/<rol>.jsonl
(tekilleştirilmiş), veri/bin/olcek/rapor.json. Kaynaklar kaynak/aday/<ad> altına seyrek (yalnız
.c/.h) ve sığ olarak, listedeki commit'te indirilir. Proje derleme betikleri (configure, cmake,
make) hiç çalıştırılmaz; yalnız clang ile dosya dosya derlenir.
"""
import argparse, hashlib, json, os, re, shutil, subprocess, sys, time
from collections import Counter, defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path, PurePosixPath

OPTS = "-O0,-O1,-O2,-O3,-Os"
OLCEK = Path("veri/bin/olcek")
UYUMLULUK = ["-fcommon", "-Wno-error=implicit-function-declaration", "-Wno-error=int-conversion",
             "-Wno-error=incompatible-pointer-types", "-Wno-error=implicit-int",
             "-Wno-error=return-type", "-D_GNU_SOURCE"]
URETILMIS = re.compile(rb"(generated by|automatically generated|auto-generated|autogenerated|"
                       rb"do not edit|don't edit|made by GNU Bison|A Bison parser|"
                       rb"generated from|this file was generated|lex\.yy\.c|re2c)", re.I)


def listeyi_oku(yollar, adlar=None, pilot=None):
    projeler = [p for y in yollar for p in json.loads(Path(y).read_text())]
    if adlar:
        projeler = [p for p in projeler if p["ad"] in adlar]
    if pilot:
        projeler = pilot_sec(projeler, pilot)
    return projeler


def pilot_sec(projeler, n):
    """Pilot: 3 mevcut proje + dağılımı yansıtan adaylar (eğitim/doğrulama/test, farklı boylar)."""
    mevcut = [p for p in projeler if "kok" not in p and p["ad"] in ("zlib", "lua", "tomlc17")]
    aday = [p for p in projeler if "kok" in p]
    test = [p for p in aday if p["rol"] == "test"][:5]
    dog = [p for p in aday if p["rol"] == "dogrulama"][:2]
    egit = sorted((p for p in aday if p["rol"] == "egitim"), key=lambda p: p.get("c_kb", 0))
    kalan = n - len(mevcut) - len(test) - len(dog)
    adim = max(1, len(egit) // max(1, kalan))
    return mevcut + test + dog + egit[::adim][:kalan]


def kok(p):
    return Path(p.get("kok") or Path("kaynak") / p["ad"])


def git(*a, cwd=None):
    r = subprocess.run(["git", *a], cwd=cwd, capture_output=True, text=True, timeout=900,
                       env={**os.environ, "GIT_TERMINAL_PROMPT": "0", "GIT_LFS_SKIP_SMUDGE": "1"})
    if r.returncode:
        raise RuntimeError(f"git {' '.join(a[:2])}: {r.stderr.strip()[-300:]}")
    return r.stdout


def indir_tek(p):
    d = kok(p)
    if (d / ".indirildi").exists() or "kok" not in p:
        return p["ad"], "var"
    if d.exists():
        shutil.rmtree(d)
    d.mkdir(parents=True)
    try:
        git("init", "-q", cwd=d)
        git("remote", "add", "origin", p["url"], cwd=d)
        git("config", "core.sparseCheckout", "true", cwd=d)
        git("config", "core.symlinks", "false", cwd=d)
        git("sparse-checkout", "set", "--no-cone", "*.c", "*.h", "*.inc", "*.def", "*.x", cwd=d)
        git("fetch", "-q", "--depth", "1", "--filter=blob:none", "origin", p["surum"], cwd=d)
        git("-c", "advice.detachedHead=false", "checkout", "-q", "FETCH_HEAD", cwd=d)
    except Exception as e:                               # indirilemeyen proje raporlanır, atlanır
        shutil.rmtree(d, ignore_errors=True)
        return p["ad"], f"hata: {e}"
    shutil.rmtree(d / ".git", ignore_errors=True)        # yer kazanmak için; commit listede kayıtlı
    (d / ".indirildi").write_text(p["surum"] + "\n")
    return p["ad"], "indirildi"


def uretilmis_dosyalar(d, dosyalar, haric):
    """İlk 2 KB'ta üretici imzası taşıyan ya da 1,5 MB'tan büyük .c dosyaları."""
    kaynaklar = {c for g in dosyalar for c in d.glob(g) if c.is_file()} - {c for h in haric for c in d.glob(h)}
    sonuc = []
    for c in sorted(kaynaklar):
        try:
            if c.stat().st_size > 1_500_000 or URETILMIS.search(c.open("rb").read(2048)):
                sonuc.append(c.relative_to(d).as_posix())
        except OSError:
            sonuc.append(c.relative_to(d).as_posix())
    return sonuc


def cikar_tek(p, opts, taslak, sure):
    d = kok(p)
    rol = p.get("rol", "egitim")
    cikti = OLCEK / "ham" / rol / f"{p['ad']}.jsonl"
    log = OLCEK / "log" / f"{p['ad']}.log"
    if cikti.exists() and cikti.with_suffix(".rapor.json").exists():
        return p["ad"], "var", 0
    if not d.is_dir():
        return p["ad"], "kaynak yok", 0
    q = dict(p)
    q["kok"] = str(d)
    if "kok" in p:                                       # aday: üretilmiş dosyaları ayıkla, uyumluluk bayrakları
        q["haric"] = list(p.get("haric", [])) + uretilmis_dosyalar(d, p.get("dosyalar", ["*.c"]), p.get("haric", []))
        q["bayraklar"] = list(p.get("bayraklar", [])) + UYUMLULUK + [f"-I{os.path.relpath(taslak.resolve(), d.resolve())}"]
    tek = OLCEK / "liste" / f"{p['ad']}.json"
    tek.parent.mkdir(parents=True, exist_ok=True)
    tek.write_text(json.dumps([q], ensure_ascii=False))
    cikti.parent.mkdir(parents=True, exist_ok=True)
    log.parent.mkdir(parents=True, exist_ok=True)
    bas = time.time()
    with log.open("w") as f:
        try:
            r = subprocess.run([sys.executable, "cikar_bin.py", "--projeler", str(tek), p["ad"], "--kip", "tam",
                                "--opts=" + opts, "--hosgoru", "--veri", str(cikti.parent)],
                               stdout=f, stderr=subprocess.STDOUT, timeout=sure)
            durum = "tamam" if r.returncode == 0 else f"hata ({r.returncode})"
        except subprocess.TimeoutExpired:
            durum = "zaman aşımı"
    return p["ad"], durum, round(time.time() - bas)


def disk_bos_gb():
    st = os.statvfs(".")
    return st.f_bavail * st.f_frsize / 2**30


def normal_asm(asm):
    s = re.sub(r"\b(sub|dat|ext)_[0-9a-f]{4,}\b", r"\1", asm)
    return hashlib.sha1(s.encode()).hexdigest()


def birlestir(rol_sirasi=("test", "dogrulama", "egitim"), alt=None):
    """Proje bazlı ayrım korunur. Normalize asm hash'i ile tekilleştirme:
    - aynı ayrım içinde ilk görülen tutulur,
    - doğrulama/test'teki bir hash eğitimde de varsa eğitimden çıkar (değerlendirme seti küçük ve değerli),
    - test ile doğrulama çakışırsa doğrulamadan çıkar,
    - doğrulama/test'te (dosya adı, fonksiyon adı) çifti eğitimde de varsa (vendored kopya) o satır çıkar."""
    kaynak = OLCEK / "ham"
    hedef = OLCEK if alt is None else OLCEK / alt
    satirlar = {r: [] for r in rol_sirasi}
    for rol in rol_sirasi:
        for f in sorted((kaynak / rol).glob("*.jsonl")) if (kaynak / rol).exists() else []:
            if alt is not None and f.stem not in alt_projeler(alt):
                continue
            satirlar[rol] += [json.loads(s) for s in f.open()]
    ham = {r: len(v) for r, v in satirlar.items()}
    hashler = {r: {} for r in rol_sirasi}
    for rol in rol_sirasi:
        for x in satirlar[rol]:
            x["_h"] = normal_asm(x["asm"])
            hashler[rol].setdefault(x["_h"], set()).add(x["ad"])
    egitim_cift = {(PurePosixPath(x["dosya"]).name, x["ad"]) for x in satirlar.get("egitim", [])}
    rapor = {"ham_satir": ham, "rol": {}}
    for rol in rol_sirasi:
        yasak = set()
        if rol == "egitim":
            yasak = set(hashler.get("test", {})) | set(hashler.get("dogrulama", {}))
        elif rol == "dogrulama":
            yasak = set(hashler.get("test", {}))
        gorulen, tut, sayac = set(), [], Counter()
        for x in satirlar[rol]:
            if x["_h"] in yasak:
                sayac["capraz_hash"] += 1
                continue
            if rol != "egitim" and (PurePosixPath(x["dosya"]).name, x["ad"]) in egitim_cift:
                sayac["vendored_cift"] += 1
                continue
            if x["_h"] in gorulen:
                sayac["tekrar_hash"] += 1
                continue
            gorulen.add(x["_h"])
            tut.append(x)
        hedef.mkdir(parents=True, exist_ok=True)
        with (hedef / f"{rol}.jsonl").open("w") as f:
            for x in tut:
                x.pop("_h")
                f.write(json.dumps(x, ensure_ascii=False) + "\n")
        rapor["rol"][rol] = {
            "proje": len({x["proje"] for x in tut}),
            "satir": len(tut),
            "benzersiz_kaynak_fonksiyon": len({(x["proje"], x["dosya"], x["ad"]) for x in tut}),
            "opt": dict(sorted(Counter(x["opt"] for x in tut).items())),
            "lisans": dict(Counter(x.get("lisans") for x in tut).most_common()),
            "lisanssiz_satir": sum(not x.get("lisans") for x in tut),
            "sizinti_isaretli": sum(x["sizinti"] for x in tut),
            "farkli_adli_ayni_hash": sum(len(v) > 1 for v in hashler[rol].values()),
            "elenen": dict(sayac)}
    (hedef / "rapor.json").write_text(json.dumps(rapor, ensure_ascii=False, indent=2) + "\n")
    return rapor


def md_rapor(projeler, alt, yol):
    """Proje bazlı durum, derleme oranı, elenen nedenleri, denetim ve örnek asm."""
    durum = json.loads((OLCEK / "durum.json").read_text())
    birlesik = json.loads(((OLCEK / alt) if alt else OLCEK).joinpath("rapor.json").read_text())
    s = [f"# Ölçekleme raporu{' — pilot' if alt else ''}", "",
         f"Projeler: {len(projeler)}; opt: {OPTS}; kip: tam; hedef x86_64-apple-macos12, Apple clang. "
         "gcc: sistemde gerçek gcc yok (/usr/bin/gcc = clang), x86-64 Mach-O hedefleyen gcc kurulmadı.", "",
         "| proje | rol | lisans | durum | sn | .c | derlenemeyen | çift | satır | O0/O1/O2/O3/Os | elenen (denetim) | atlanan opt |",
         "|---|---|---|---|---:|---:|---:|---:|---:|---|---:|---|"]
    toplam = Counter()
    for p in projeler:
        rol = p.get("rol", "egitim")
        r_yol = OLCEK / "ham" / rol / f"{p['ad']}.rapor.json"
        d = durum.get(p["ad"], {})
        if not r_yol.exists():
            s.append(f"| {p['ad']} | {rol} | {p.get('lisans')} | {d.get('indir', '')} {d.get('cikar', 'yok')} | "
                     f"{d.get('sure_sn', '')} | | | | 0 | | | |")
            toplam["basarisiz"] += 1
            continue
        r = json.loads(r_yol.read_text())
        o = r["optimizasyonlar"]
        satir = {k: v["kipler"].get("tam", {}).get("satir", 0) for k, v in o.items()}
        derlenemeyen = max((len(v["derlenemeyen"]) for v in o.values()), default=r["kaynak_dosya"])
        cift = max((len(v["cift_sembol_atilan"]) for v in o.values()), default=0)
        denetim = sum(v["kipler"].get("tam", {}).get("elenen", {}).get("denetim", 0) for v in o.values())
        toplam["satir"] += sum(satir.values())
        toplam["denetim"] += denetim
        toplam["basarili" if satir else "bos"] += 1
        s.append(f"| {p['ad']} | {rol} | {p.get('lisans')} | {d.get('cikar', '')} | {d.get('sure_sn', '')} | "
                 f"{r['kaynak_dosya']} | {derlenemeyen} | {cift} | {sum(satir.values())} | "
                 + "/".join(str(satir.get(k, '-')) for k in OPTS.split(",")) + f" | {denetim} | "
                 + ", ".join(f"{k}: {v[:60]}" for k, v in r["atlanan_opt"].items()) + " |")
    s += ["", f"Toplam ham satır {toplam['satir']}, denetimle elenen {toplam['denetim']}; "
          f"satır üreten {toplam['basarili']}, boş {toplam['bos']}, başarısız {toplam['basarisiz']}.", "",
          "## Birleştirme (tekilleştirme + ayrım)", "", "```json",
          json.dumps(birlesik, ensure_ascii=False, indent=1), "```", "", "## Örnek satırlar", ""]
    for rol in ("egitim", "test"):
        f = ((OLCEK / alt) if alt else OLCEK) / f"{rol}.jsonl"
        if not f.exists():
            continue
        ornek = [json.loads(x) for x in f.open()]
        ornek = [x for x in ornek if 15 <= x["komut_sayisi"] <= 40 and x["proje"] not in ("zlib", "lua")]
        for x in ornek[:: max(1, len(ornek) // 2)][:2]:
            s += [f"**{x['id']}** ({x['lisans'] if 'lisans' in x else '?'}; {x['komut_sayisi']} komut; "
                  f"sızıntı={x['sizinti']})", "", "```asm", x["asm"], "```",
                  *(["bağlam:", "```", x["baglam"], "```"] if x["baglam"] else []), ""]
    yol.parent.mkdir(parents=True, exist_ok=True)
    yol.write_text("\n".join(s) + "\n")
    print(f"rapor → {yol}")


def alt_projeler(alt):
    return set(json.loads((OLCEK / alt / "projeler.json").read_text()))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("adim", choices=("indir", "cikar", "birlestir", "rapor", "hepsi"))
    ap.add_argument("--rapor", type=Path, default=Path(".notlar/olcek/rapor.md"))
    ap.add_argument("--liste", nargs="+", default=["projeler.json", ".notlar/aday-projeler.json"])
    ap.add_argument("--ad", nargs="*")
    ap.add_argument("--pilot", type=int)
    ap.add_argument("--opts", default=OPTS)
    ap.add_argument("-j", type=int, default=3, help="aynı anda kaç proje")
    ap.add_argument("--sure", type=int, default=3600, help="proje başına saniye")
    ap.add_argument("--min-disk", type=float, default=6.0, help="GB; altına inince yeni iş başlatma")
    a = ap.parse_args()
    projeler = listeyi_oku(a.liste, a.ad, a.pilot)
    alt = "pilot" if a.pilot else None
    if alt:
        (OLCEK / alt).mkdir(parents=True, exist_ok=True)
        (OLCEK / alt / "projeler.json").write_text(json.dumps([p["ad"] for p in projeler]) + "\n")
    durum_yolu = OLCEK / "durum.json"
    durum = json.loads(durum_yolu.read_text()) if durum_yolu.exists() else {}

    def kaydet():
        durum_yolu.parent.mkdir(parents=True, exist_ok=True)
        durum_yolu.write_text(json.dumps(durum, ensure_ascii=False, indent=1) + "\n")

    if a.adim in ("indir", "hepsi"):
        with ThreadPoolExecutor(6) as h:
            for ad, s in h.map(indir_tek, projeler):
                durum.setdefault(ad, {})["indir"] = s
                print(f"indir {ad}: {s}", flush=True)
        kaydet()
    if a.adim in ("cikar", "hepsi"):
        taslak = OLCEK / "taslak"                      # boş config.h: üretilmemiş yapılandırma başlığı
        taslak.mkdir(parents=True, exist_ok=True)
        for b in ("config.h",):
            (taslak / b).write_text("/* asmsense: boş yer tutucu */\n")
        with ThreadPoolExecutor(a.j) as h:
            isler = {}
            for p in projeler:
                while disk_bos_gb() < a.min_disk:
                    print(f"disk {disk_bos_gb():.1f} GB < {a.min_disk}; bekleniyor", flush=True)
                    time.sleep(120)
                isler[h.submit(cikar_tek, p, a.opts, taslak, a.sure)] = p
            for i, f in enumerate(as_completed(isler), 1):
                ad, s, sn = f.result()
                durum.setdefault(ad, {})["cikar"] = s
                durum[ad]["sure_sn"] = sn
                print(f"[{i}/{len(isler)}] cikar {ad}: {s} ({sn} sn, disk {disk_bos_gb():.1f} GB)", flush=True)
                kaydet()
    if a.adim in ("birlestir", "hepsi"):
        print(json.dumps(birlestir(alt=alt), ensure_ascii=False, indent=1))
    if a.adim in ("rapor", "hepsi"):
        md_rapor(projeler, alt, a.rapor)


if __name__ == "__main__":
    main()
